version: '3.8'

services:
  redis-service2:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  service1:
    build:
      context: ./1st
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    # healthcheck:
    #   test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
    #   interval: 10s
    #   timeout: 2s
    #   retries: 5

  service2:
    build:
      context: ./2nd
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mynetwork
    environment:
      - service1Url=http://service1:8080/generate/json/
      - REDIS_HOST=redis-service2
      - REDIS_PORT=6379
    depends_on:
      - service1
      - redis-service2

  # service3:
  #   build:
  #     context: ./3rd
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8082"
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - service1
  #     - service2

networks:
  mynetwork:
    driver: bridge
